# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from datetime import date
from typing import cast

from psycopg import Connection

from .._runtime import fetch_single
from ..types.album_format import AlbumFormat
from ..types.recording_info import RecordingInfo


@dataclass(frozen=True, slots=True)
class InsertAlbumRow:
    id: int


def decode_insert_album(row: Mapping[str, object]) -> InsertAlbumRow:
    return InsertAlbumRow(
        id=cast(int, row["id"]),
    )


SQL = """\
insert into album (name, released, format, recording)
values (%(name)s, %(released)s, %(format)s, %(recording)s)
returning id
"""

_SQL = SQL.encode()


def insert_album(
    conn: Connection[object],
    *,
    name: str,
    released: date,
    format: AlbumFormat,
    recording: RecordingInfo,
) -> InsertAlbumRow:
    params: dict[str, object] = {
        "name": name,
        "released": released,
        "format": format.pg_encode(),
        "recording": recording.pg_encode(),
    }
    return fetch_single(conn, _SQL, params, decode_insert_album)
