# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from datetime import date
from typing import cast

from psycopg import Connection

from .._runtime import fetch_many
from ..types.album_format import AlbumFormat


@dataclass(frozen=True, slots=True)
class InsertMultipleAlbumsRow:
    id: int


def decode_insert_multiple_albums(row: Mapping[str, object]) -> InsertMultipleAlbumsRow:
    return InsertMultipleAlbumsRow(
        id=cast(int, row["id"]),
    )


SQL = """\
-- This is an example of a bulk-insert (batch-insert) technique.
-- We pass in all fields as arrays of the same size, and we unnest it to insert multiple rows at once.
insert into album (name, released, format)
select *
from unnest(
  %(name)s::text[],
  %(released)s::date[],
  %(format)s::album_format[]
)
returning id
"""

_SQL = SQL.encode()


def insert_multiple_albums(
    conn: Connection[object],
    *,
    name: list[str],
    released: list[date],
    format: list[AlbumFormat],
) -> list[InsertMultipleAlbumsRow]:
    params: dict[str, object] = {
        "name": name,
        "released": released,
        "format": [x.pg_encode() for x in format],
    }
    return fetch_many(conn, _SQL, params, decode_insert_multiple_albums)
