# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from datetime import date, datetime
from typing import cast

from psycopg import Connection

from .._core import require_array
from .._runtime import fetch_many
from ..types.album_format import AlbumFormat
from ..types.album_format import AlbumFormat
from ..types.recording_info import RecordingInfo
from ..types.track_info import TrackInfo
from ..types.disc_info import DiscInfo


@dataclass(frozen=True, slots=True)
class SelectAlbumWithFiltersRow:
    id: int
    name: str | None
    released: date | None
    format: AlbumFormat | None
    recording: RecordingInfo | None
    tracks: list[TrackInfo] | None
    disc: DiscInfo | None


def decode_select_album_with_filters(row: Mapping[str, object]) -> SelectAlbumWithFiltersRow:
    return SelectAlbumWithFiltersRow(
        id=cast(int, row["id"]),
        name=cast(str | None, row["name"]),
        released=cast(date | None, row["released"]),
        format=None if row["format"] is None else AlbumFormat.pg_decode(row["format"]),
        recording=None if row["recording"] is None else RecordingInfo.pg_decode(row["recording"]),
        tracks=None if row["tracks"] is None else [TrackInfo.pg_decode(v) for v in cast(list[str], require_array(row["tracks"]))],
        disc=None if row["disc"] is None else DiscInfo.pg_decode(row["disc"]),
    )


SQL = """\
-- Demonstrates static query equivalent of dynamic field selection.
-- Boolean flags control which fields are included in the result,
-- returning NULL for fields the caller opts out of.
-- Also demonstrates optional filters and ordering criteria.
SELECT
  album.id,
  CASE WHEN %(include_name)s THEN album.name END AS name,
  CASE WHEN %(include_released)s THEN album.released END AS released,
  CASE WHEN %(include_format)s THEN album.format END AS format,
  CASE WHEN %(include_recording)s THEN album.recording END AS recording,
  CASE WHEN %(include_tracks)s THEN album.tracks END AS tracks,
  CASE WHEN %(include_disc)s THEN album.disc END AS disc
FROM album
LEFT JOIN album_artist ON album_artist.album = album.id
LEFT JOIN artist ON artist.id = album_artist.artist
LEFT JOIN album_genre ON album_genre.album = album.id
LEFT JOIN genre ON genre.id = album_genre.genre
WHERE
  (%(artist_name)s::text IS NULL OR artist.name = %(artist_name)s)
  AND (%(genre_name)s::text IS NULL OR genre.name = %(genre_name)s)
  AND (%(format)s::album_format IS NULL OR album.format = %(format)s)
  AND (%(released_after)s::timestamp IS NULL OR album.released >= %(released_after)s)
  AND (%(name_like)s::text IS NULL OR album.name LIKE %(name_like)s)
ORDER BY
  CASE WHEN %(order_by_name)s THEN album.name END ASC,
  CASE WHEN %(order_by_released)s THEN album.released END DESC
"""

_SQL = SQL.encode()


def select_album_with_filters(
    conn: Connection[object],
    *,
    include_name: bool,
    include_released: bool,
    include_format: bool,
    include_recording: bool,
    include_tracks: bool,
    include_disc: bool,
    artist_name: str | None,
    genre_name: str | None,
    format: AlbumFormat | None,
    released_after: datetime | None,
    name_like: str | None,
    order_by_name: bool,
    order_by_released: bool,
) -> list[SelectAlbumWithFiltersRow]:
    params: dict[str, object] = {
        "include_name": include_name,
        "include_released": include_released,
        "include_format": include_format,
        "include_recording": include_recording,
        "include_tracks": include_tracks,
        "include_disc": include_disc,
        "artist_name": artist_name,
        "genre_name": genre_name,
        "format": None if format is None else format.pg_encode(),
        "released_after": released_after,
        "name_like": name_like,
        "order_by_name": order_by_name,
        "order_by_released": order_by_released,
    }
    return fetch_many(conn, _SQL, params, decode_select_album_with_filters)
