# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from datetime import date
from typing import cast

from psycopg import Connection

from .._core import require_array
from .._runtime import fetch_optional
from ..types.album_format import AlbumFormat
from ..types.recording_info import RecordingInfo
from ..types.track_info import TrackInfo
from ..types.disc_info import DiscInfo


@dataclass(frozen=True, slots=True)
class SelectAlbumByIdRow:
    id: int
    name: str
    released: date | None
    format: AlbumFormat | None
    recording: RecordingInfo | None
    tracks: list[TrackInfo | None] | None
    disc: DiscInfo | None


def decode_select_album_by_id(row: Mapping[str, object]) -> SelectAlbumByIdRow:
    return SelectAlbumByIdRow(
        id=cast(int, row["id"]),
        name=cast(str, row["name"]),
        released=cast(date | None, row["released"]),
        format=None if row["format"] is None else AlbumFormat.pg_decode(row["format"]),
        recording=None if row["recording"] is None else RecordingInfo.pg_decode(row["recording"]),
        tracks=None if row["tracks"] is None else [None if v is None else TrackInfo.pg_decode(v) for v in cast(list[str | None], require_array(row["tracks"]))],
        disc=None if row["disc"] is None else DiscInfo.pg_decode(row["disc"]),
    )


SQL = """\
-- Example of a query selecting 0 or 1 row.
select *
from album
where id = %(id)s
limit 1
"""

_SQL = SQL.encode()


def select_album_by_id(
    conn: Connection[object],
    *,
    id: int | None,
) -> SelectAlbumByIdRow | None:
    params: dict[str, object] = {
        "id": id,
    }
    return fetch_optional(conn, _SQL, params, decode_select_album_by_id)
