# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from datetime import date
from typing import cast

from psycopg import Connection

from .._runtime import fetch_many
from ..types.album_format import AlbumFormat
from ..types.album_format import AlbumFormat
from ..types.recording_info import RecordingInfo


@dataclass(frozen=True, slots=True)
class SelectAlbumByFormatRow:
    id: int
    name: str
    released: date | None
    format: AlbumFormat | None
    recording: RecordingInfo | None


def decode_select_album_by_format(row: Mapping[str, object]) -> SelectAlbumByFormatRow:
    return SelectAlbumByFormatRow(
        id=cast(int, row["id"]),
        name=cast(str, row["name"]),
        released=cast(date | None, row["released"]),
        format=None if row["format"] is None else AlbumFormat.pg_decode(row["format"]),
        recording=None if row["recording"] is None else RecordingInfo.pg_decode(row["recording"]),
    )


SQL = """\
select 
  id,
  name,
  released,
  format,
  recording
from album
where format = %(format)s
"""

_SQL = SQL.encode()


def select_album_by_format(
    conn: Connection[object],
    *,
    format: AlbumFormat,
) -> list[SelectAlbumByFormatRow]:
    params: dict[str, object] = {
        "format": format.pg_encode(),
    }
    return fetch_many(conn, _SQL, params, decode_select_album_by_format)
