# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import cast

from psycopg import Connection

from .._runtime import fetch_many


@dataclass(frozen=True, slots=True)
class SelectGenreByArtistRow:
    id: int
    name: str


def decode_select_genre_by_artist(row: Mapping[str, object]) -> SelectGenreByArtistRow:
    return SelectGenreByArtistRow(
        id=cast(int, row["id"]),
        name=cast(str, row["name"]),
    )


SQL = """\
select id, genre.name
from genre
left join album_genre on album_genre.genre = genre.id
left join album_artist on album_artist.album = album_genre.album
where album_artist.artist = %(artist)s
"""

_SQL = SQL.encode()


def select_genre_by_artist(
    conn: Connection[object],
    *,
    artist: int,
) -> list[SelectGenreByArtistRow]:
    params: dict[str, object] = {
        "artist": artist,
    }
    return fetch_many(conn, _SQL, params, decode_select_genre_by_artist)
