# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from datetime import date

from psycopg import Connection

from .._runtime import execute_rows_affected

SQL = """\
update album
set released = %(released)s
where id = %(id)s
"""

_SQL = SQL.encode()


def update_album_released(
    conn: Connection[object],
    *,
    released: date | None,
    id: int,
) -> int:
    params: dict[str, object] = {
        "released": released,
        "id": id,
    }
    return execute_rows_affected(conn, _SQL, params)
