# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from .album_format import AlbumFormat as AlbumFormat
from .disc_info import DiscInfo as DiscInfo
from .recording_info import RecordingInfo as RecordingInfo
from .track_info import TrackInfo as TrackInfo
