# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from enum import StrEnum


class AlbumFormat(StrEnum):
    VINYL = "Vinyl"
    CD = "CD"
    CASSETTE = "Cassette"
    DIGITAL = "Digital"
    DVD_AUDIO = "DVD-Audio"
    SACD = "SACD"
