# Projects namespace.
# In case of personal projects it's your username,
# in case of organization projects it's the organization name.
# Affects the namespacing in the generated artifacts.
space: my-space
# Name of the project.
# Affects the namespacing in the generated artifacts.
name: music-catalogue
# Source directory of schema migrations.
# When this setting is missing "migrations" is actually implied,
# so we're only specifying it for the demonstration purposes here.
migrations-dir: migrations
# Source directory of queries.
# When this setting is missing "queries" is actually implied,
# so we're only specifying it for the demonstration purposes here.
queries-dir: queries
# Directory where the generated artifacts will be put.
# When this setting is missing "artifacts" is actually implied,
# so we're only specifying it for the demonstration purposes here.
artifacts-dir: artifacts
# Artifacts that we want Pgenie to produce.
# I.e., libraries for various platforms.
# If you don't specify any artifacts Pgenie simply validates your schema
# and queries.
artifacts:
  - haskell-hasql
  - java-jdbc
