# Projects namespace.
# In case of personal projects it's your username,
# in case of organization projects it's the organization name.
# Affects the namespacing in the generated artifacts.
space: my-space

# Name of the project.
# Affects the namespacing in the generated artifacts.
name: music-catalogue

# Version to be used in the generated artifacts.
# The convention is [SemVer](https://semver.org/).
# 
# In case of Haskell the version will be prepended with "0."
# to comply to the PVP convention.
version: 1.0.0

# Artifacts that we want Pgenie to produce.
# I.e., libraries for various platforms.
# If you don't specify any artifacts Pgenie simply validates your schema
# and queries.
artifacts:
  - haskell-hasql-v1
  - java-jdbc-v1
