# Projects space.
# In case of personal projects it's your username,
# in case of organization projects it's the organization.
# Affects the namespacing in the generated artifacts.
space: my-space
# Name of the project.
# Affects the namespacing in the generated artifacts.
name: music-catalogue
# Directory where the generated artifacts will be put.
# When this setting is missing "artifacts" is actually implied,
# so we're only specifying it for the demonstration purposes here.
artifacts-dir: artifacts
# Artifacts that we want Pgenie to produce.
# It is libraries for various platforms.
# Specifying no artifacts is valid.
# In such case Pgenie simply validate your schema
# and queries against it.
artifacts:
  - haskell-hasql
  - java-jdbc
