# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from psycopg import AsyncConnection
from psycopg.types import TypeInfo
from psycopg.types.composite import CompositeInfo, register_composite


_COMPOSITE_TYPES = ("public.album", "public.disc_info", "public.recording_info", "public.track_info",)
_ENUM_TYPES = ("public.album_format",)


async def register_types(conn: AsyncConnection[object]) -> None:
    for name in _COMPOSITE_TYPES:
        composite_info = await CompositeInfo.fetch(conn, name)
        if composite_info is None:
            raise LookupError(f"composite type {name!r} not found; cannot register it")
        register_composite(composite_info, conn)
    for name in _ENUM_TYPES:
        enum_info = await TypeInfo.fetch(conn, name)
        if enum_info is None:
            raise LookupError(f"enum type {name!r} not found; cannot register it")
        enum_info.register(conn)
