# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from collections.abc import Callable, Mapping
from typing import TypeVar

from psycopg import AsyncConnection
from psycopg.rows import dict_row

from ._core import JsonValue as JsonValue, NoRowError as NoRowError, require_array as require_array

_T = TypeVar("_T")
_Row = Mapping[str, object]
_Params = Mapping[str, object]


async def fetch_optional(
    conn: AsyncConnection[object],
    sql: bytes,
    params: _Params,
    decode: Callable[[_Row], _T],
) -> _T | None:
    async with conn.cursor(row_factory=dict_row) as cur:
        _ = await cur.execute(sql, params)
        row = await cur.fetchone()
    return None if row is None else decode(row)


async def fetch_single(
    conn: AsyncConnection[object],
    sql: bytes,
    params: _Params,
    decode: Callable[[_Row], _T],
) -> _T:
    async with conn.cursor(row_factory=dict_row) as cur:
        _ = await cur.execute(sql, params)
        row = await cur.fetchone()
    if row is None:
        raise NoRowError(sql.decode())
    return decode(row)


async def fetch_many(
    conn: AsyncConnection[object],
    sql: bytes,
    params: _Params,
    decode: Callable[[_Row], _T],
) -> list[_T]:
    async with conn.cursor(row_factory=dict_row) as cur:
        _ = await cur.execute(sql, params)
        rows = await cur.fetchall()
    return [decode(row) for row in rows]


async def execute_rows_affected(
    conn: AsyncConnection[object],
    sql: bytes,
    params: _Params,
) -> int:
    async with conn.cursor() as cur:
        _ = await cur.execute(sql, params)
        return cur.rowcount


async def execute_void(
    conn: AsyncConnection[object],
    sql: bytes,
    params: _Params,
) -> None:
    async with conn.cursor() as cur:
        _ = await cur.execute(sql, params)
