# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from dataclasses import dataclass
from typing import cast

from datetime import date


@dataclass(frozen=True, slots=True)
class RecordingInfo:
    """Decoding/encoding this composite requires register_types(conn) first.

    Without per-connection registration psycopg returns the value as a
    raw string, which the generated pg_decode cannot splat into the dataclass.
    """

    studio_name: str
    city: str
    country: str
    recorded_date: date

    @staticmethod
    def pg_decode(src: object) -> "RecordingInfo":
        return RecordingInfo(*cast(tuple[str, str, str, date], src))

    def pg_encode(self) -> tuple[str, str, str, date]:
        return (self.studio_name, self.city, self.country, self.recorded_date)
