# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from .._generated._core import (
    JsonValue as JsonValue,
)
from .._generated._core import (
    NoRowError as NoRowError,
)
from .._generated._register import (
    register_types_sync as register_types,
)

# isort: off
from .._generated.statements.insert_album import (
    InsertAlbumRow as InsertAlbumRow,
)
from .._generated.statements.insert_album import (
    insert_album_sync as insert_album,
)
from .._generated.statements.insert_multiple_albums import (
    InsertMultipleAlbumsRow as InsertMultipleAlbumsRow,
)
from .._generated.statements.insert_multiple_albums import (
    insert_multiple_albums_sync as insert_multiple_albums,
)
from .._generated.statements.select_album_by_format import (
    SelectAlbumByFormatRow as SelectAlbumByFormatRow,
)
from .._generated.statements.select_album_by_format import (
    select_album_by_format_sync as select_album_by_format,
)
from .._generated.statements.select_album_by_id import (
    SelectAlbumByIdRow as SelectAlbumByIdRow,
)
from .._generated.statements.select_album_by_id import (
    select_album_by_id_sync as select_album_by_id,
)
from .._generated.statements.select_album_by_name import (
    SelectAlbumByNameRow as SelectAlbumByNameRow,
)
from .._generated.statements.select_album_by_name import (
    select_album_by_name_sync as select_album_by_name,
)
from .._generated.statements.select_album_with_filters import (
    SelectAlbumWithFiltersRow as SelectAlbumWithFiltersRow,
)
from .._generated.statements.select_album_with_filters import (
    select_album_with_filters_sync as select_album_with_filters,
)
from .._generated.statements.select_album_with_tracks import (
    SelectAlbumWithTracksRow as SelectAlbumWithTracksRow,
)
from .._generated.statements.select_album_with_tracks import (
    select_album_with_tracks_sync as select_album_with_tracks,
)
from .._generated.statements.select_genre_by_artist import (
    SelectGenreByArtistRow as SelectGenreByArtistRow,
)
from .._generated.statements.select_genre_by_artist import (
    select_genre_by_artist_sync as select_genre_by_artist,
)
from .._generated.statements.update_album_recording_returning import (
    UpdateAlbumRecordingReturningRow as UpdateAlbumRecordingReturningRow,
)
from .._generated.statements.update_album_recording_returning import (
    update_album_recording_returning_sync as update_album_recording_returning,
)
from .._generated.statements.update_album_released import (
    update_album_released_sync as update_album_released,
)
# isort: on

# isort: off
from .._generated.types.album_format import (
    AlbumFormat as AlbumFormat,
)
from .._generated.types.recording_info import (
    RecordingInfo as RecordingInfo,
)
from .._generated.types.disc_info import (
    DiscInfo as DiscInfo,
)
from .._generated.types.track_info import (
    TrackInfo as TrackInfo,
)
# isort: on

__all__ = [
    "JsonValue",
    "NoRowError",
]
# Project order is intentional for public re-export groups.
__all__ += [  # noqa: RUF022, RUF100
    "AlbumFormat",
    "RecordingInfo",
    "DiscInfo",
    "TrackInfo",
]
__all__ += [  # noqa: RUF022, RUF100
    "InsertAlbumRow",
    "InsertMultipleAlbumsRow",
    "SelectAlbumByFormatRow",
    "SelectAlbumByIdRow",
    "SelectAlbumByNameRow",
    "SelectAlbumWithFiltersRow",
    "SelectAlbumWithTracksRow",
    "SelectGenreByArtistRow",
    "UpdateAlbumRecordingReturningRow",
]
__all__ += [  # noqa: RUF022, RUF100
    "insert_album",
    "insert_multiple_albums",
    "select_album_by_format",
    "select_album_by_id",
    "select_album_by_name",
    "select_album_with_filters",
    "select_album_with_tracks",
    "select_genre_by_artist",
    "update_album_recording_returning",
    "update_album_released",
]
__all__ += [
    "register_types",
]
