# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from dataclasses import dataclass

from .recording_info import RecordingInfo


@dataclass(frozen=True, slots=True)
class DiscInfo:
    name: str | None
    recording: RecordingInfo | None
