# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from dataclasses import dataclass

from datetime import date


@dataclass(frozen=True, slots=True)
class RecordingInfo:
    studio_name: str
    city: str
    country: str
    recorded_date: date
