# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class TrackInfo:
    title: str
    duration_seconds: int
    tags: list[str]
