# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

"""Shared types and decode helpers, surface-agnostic; no I/O."""

from __future__ import annotations

from typing import cast

type JsonValue = None | bool | int | float | str | list["JsonValue"] | dict[str, "JsonValue"]


class NoRowError(RuntimeError):
    """A single-row query returned no rows."""


class DecodeError(RuntimeError):
    """A row value failed to decode into its target type."""


def require_array(value: object) -> list[object]:
    """Guard an enum-array column decode.

    psycopg returns an enum array as a Python list only when the enum type is
    registered on the connection (register_types); without it the value comes
    back as the raw array text, which would iterate into bogus members. Fail
    clearly instead.
    """
    if isinstance(value, list):
        return cast(list[object], value)
    raise RuntimeError(
        "enum array decoded as text; call register_types() on the connection "
        "before decoding enum-array columns"
    )
