# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from dataclasses import dataclass

from psycopg import AsyncConnection, Connection
from psycopg.rows import args_row as _args_row

from .._runtime import fetch_many as _fetch_many
from ..sync._runtime import fetch_many as _fetch_many_sync

SQL = """\
select id, genre.name
from genre
left join album_genre on album_genre.genre = genre.id
left join album_artist on album_artist.album = album_genre.album
where album_artist.artist = %(artist)s
"""


@dataclass(frozen=True, slots=True)
class SelectGenreByArtistRow:
    id: int
    name: str


async def select_genre_by_artist(
    conn: AsyncConnection[object],
    *,
    artist: int,
) -> list[SelectGenreByArtistRow]:
    params: dict[str, object] = {
        "artist": artist,
    }
    return await _fetch_many(conn, SQL, params, _args_row(SelectGenreByArtistRow))


def select_genre_by_artist_sync(
    conn: Connection[object],
    *,
    artist: int,
) -> list[SelectGenreByArtistRow]:
    params: dict[str, object] = {
        "artist": artist,
    }
    return _fetch_many_sync(conn, SQL, params, _args_row(SelectGenreByArtistRow))
