# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from dataclasses import dataclass
from datetime import date

from psycopg import AsyncConnection, Connection
from psycopg.rows import args_row as _args_row

from .. import types as _db_types
from .._runtime import fetch_optional as _fetch_optional
from ..sync._runtime import fetch_optional as _fetch_optional_sync

SQL = """\
-- Example of a query selecting 0 or 1 row.
select *
from album
where id = %(id)s
limit 1
"""


@dataclass(frozen=True, slots=True)
class SelectAlbumByIdRow:
    id: int
    name: str
    released: date | None
    format: _db_types.AlbumFormat | None
    recording: _db_types.RecordingInfo | None
    tracks: list[_db_types.TrackInfo | None] | None
    disc: _db_types.DiscInfo | None


async def select_album_by_id(
    conn: AsyncConnection[object],
    *,
    id: int | None,
) -> SelectAlbumByIdRow | None:
    params: dict[str, object] = {
        "id": id,
    }
    return await _fetch_optional(conn, SQL, params, _args_row(SelectAlbumByIdRow))


def select_album_by_id_sync(
    conn: Connection[object],
    *,
    id: int | None,
) -> SelectAlbumByIdRow | None:
    params: dict[str, object] = {
        "id": id,
    }
    return _fetch_optional_sync(conn, SQL, params, _args_row(SelectAlbumByIdRow))
