# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from dataclasses import dataclass

from psycopg import AsyncConnection, Connection
from psycopg.rows import args_row as _args_row

from .. import types as _db_types
from .._runtime import fetch_many as _fetch_many
from ..sync._runtime import fetch_many as _fetch_many_sync

SQL = """\
select id, name, tracks, disc
from album
where id = %(id)s
"""


@dataclass(frozen=True, slots=True)
class SelectAlbumWithTracksRow:
    id: int
    name: str
    tracks: list[_db_types.TrackInfo]
    disc: _db_types.DiscInfo | None


async def select_album_with_tracks(
    conn: AsyncConnection[object],
    *,
    id: int,
) -> list[SelectAlbumWithTracksRow]:
    params: dict[str, object] = {
        "id": id,
    }
    return await _fetch_many(conn, SQL, params, _args_row(SelectAlbumWithTracksRow))


def select_album_with_tracks_sync(
    conn: Connection[object],
    *,
    id: int,
) -> list[SelectAlbumWithTracksRow]:
    params: dict[str, object] = {
        "id": id,
    }
    return _fetch_many_sync(conn, SQL, params, _args_row(SelectAlbumWithTracksRow))
