# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from enum import StrEnum
from typing import cast


class AlbumFormat(StrEnum):
    VINYL = "Vinyl"
    CD = "CD"
    CASSETTE = "Cassette"
    DIGITAL = "Digital"
    DVD_AUDIO = "DVD-Audio"
    SACD = "SACD"

    @staticmethod
    def pg_decode(src: object) -> "AlbumFormat":
        return AlbumFormat(cast(str, src))

    def pg_encode(self) -> "AlbumFormat":
        return self
