# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from dataclasses import dataclass
from typing import cast

from datetime import date


@dataclass(frozen=True, slots=True)
class Album:
    """Decoding/encoding this composite requires register_types(conn) first.

    Without per-connection registration psycopg returns the value as a
    raw string, which the generated pg_decode cannot splat into the dataclass.
    """

    id: int | None
    name: str | None
    released: date | None
    format: AlbumFormat | None
    recording: RecordingInfo | None
    tracks: list[TrackInfo | None] | None
    disc: DiscInfo | None

    @staticmethod
    def pg_decode(src: object) -> "Album":
        return Album(*cast(tuple[int | None, str | None, date | None, AlbumFormat | None, RecordingInfo | None, list[TrackInfo | None] | None, DiscInfo | None], src))

    def pg_encode(self) -> tuple[int | None, str | None, date | None, AlbumFormat | None, RecordingInfo | None, list[TrackInfo | None] | None, DiscInfo | None]:
        return (self.id, self.name, self.released, self.format, self.recording, self.tracks, self.disc)
