# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from dataclasses import dataclass
from typing import cast


@dataclass(frozen=True, slots=True)
class DiscInfo:
    """Decoding/encoding this composite requires register_types(conn) first.

    Without per-connection registration psycopg returns the value as a
    raw string, which the generated pg_decode cannot splat into the dataclass.
    """

    name: str | None
    recording: RecordingInfo | None

    @staticmethod
    def pg_decode(src: object) -> "DiscInfo":
        return DiscInfo(*cast(tuple[str | None, RecordingInfo | None], src))

    def pg_encode(self) -> tuple[str | None, RecordingInfo | None]:
        return (self.name, self.recording)
