# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from dataclasses import dataclass
from typing import cast


@dataclass(frozen=True, slots=True)
class TrackInfo:
    """Decoding/encoding this composite requires register_types(conn) first.

    Without per-connection registration psycopg returns the value as a
    raw string, which the generated pg_decode cannot splat into the dataclass.
    """

    title: str
    duration_seconds: int
    tags: list[str]

    @staticmethod
    def pg_decode(src: object) -> "TrackInfo":
        return TrackInfo(*cast(tuple[str, int, list[str]], src))

    def pg_encode(self) -> tuple[str, int, list[str]]:
        return (self.title, self.duration_seconds, self.tags)
