# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

"""Shared types and errors, surface-agnostic; no I/O."""

from __future__ import annotations

type JsonValue = None | bool | int | float | str | list["JsonValue"] | dict[str, "JsonValue"]


class NoRowError(RuntimeError):
    """A single-row query returned no rows."""

    def __init__(self, sql: str) -> None:
        self.sql = sql
        super().__init__(f"single-row query returned no rows: {sql}")
