# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

import keyword
from collections.abc import Callable, Sequence
from dataclasses import fields, is_dataclass
from typing import Any

from psycopg import AsyncConnection, Connection
from psycopg.types.composite import CompositeInfo, register_composite
from psycopg.types.enum import EnumInfo, register_enum

from . import types as _db_types

type _ObjectMaker[T] = Callable[[Sequence[Any], CompositeInfo], T]
type _SequenceMaker[T] = Callable[[T, CompositeInfo], Sequence[Any]]


def _python_name(name: str) -> str:
    if keyword.iskeyword(name):
        return f"{name}_"
    return name


def _dataclass_callbacks[T](cls: type[T]) -> tuple[_ObjectMaker[T], _SequenceMaker[T]]:
    if not is_dataclass(cls):
        raise TypeError(f"{cls.__name__} must be a dataclass")

    model_fields = fields(cls)
    model_names = tuple(field.name for field in model_fields)

    def make_object(values: Sequence[Any], info: CompositeInfo) -> T:
        names = tuple(_python_name(name) for name in info.field_names)
        assert names == model_names
        assert len(values) == len(model_fields)
        return cls(**dict(zip(names, values, strict=True)))

    def make_sequence(obj: T, info: CompositeInfo) -> Sequence[Any]:
        names = tuple(_python_name(name) for name in info.field_names)
        assert names == model_names
        return tuple(getattr(obj, field.name) for field in model_fields)

    return make_object, make_sequence


_album_format_pg_name = "public.album_format"
_recording_info_pg_name = "public.recording_info"
_recording_info_make_object, _recording_info_make_sequence = _dataclass_callbacks(_db_types.RecordingInfo)
_track_info_pg_name = "public.track_info"
_track_info_make_object, _track_info_make_sequence = _dataclass_callbacks(_db_types.TrackInfo)
_disc_info_pg_name = "public.disc_info"
_disc_info_make_object, _disc_info_make_sequence = _dataclass_callbacks(_db_types.DiscInfo)


async def register_types(conn: AsyncConnection[object]) -> None:
    album_format_info = await EnumInfo.fetch(conn, _album_format_pg_name)
    if album_format_info is None:
        raise LookupError(f"enum type {_album_format_pg_name!r} not found; cannot register it")
    register_enum(
        album_format_info,
        conn,
        _db_types.AlbumFormat,
        mapping={member: member.value for member in _db_types.AlbumFormat},
    )
    recording_info_info = await CompositeInfo.fetch(conn, _recording_info_pg_name)
    if recording_info_info is None:
        raise LookupError(f"composite type {_recording_info_pg_name!r} not found; cannot register it")
    register_composite(
        recording_info_info,
        conn,
        _db_types.RecordingInfo,
        make_object=_recording_info_make_object,
        make_sequence=_recording_info_make_sequence,
    )
    track_info_info = await CompositeInfo.fetch(conn, _track_info_pg_name)
    if track_info_info is None:
        raise LookupError(f"composite type {_track_info_pg_name!r} not found; cannot register it")
    register_composite(
        track_info_info,
        conn,
        _db_types.TrackInfo,
        make_object=_track_info_make_object,
        make_sequence=_track_info_make_sequence,
    )
    disc_info_info = await CompositeInfo.fetch(conn, _disc_info_pg_name)
    if disc_info_info is None:
        raise LookupError(f"composite type {_disc_info_pg_name!r} not found; cannot register it")
    register_composite(
        disc_info_info,
        conn,
        _db_types.DiscInfo,
        make_object=_disc_info_make_object,
        make_sequence=_disc_info_make_sequence,
    )


def register_types_sync(conn: Connection[object]) -> None:
    album_format_info = EnumInfo.fetch(conn, _album_format_pg_name)
    if album_format_info is None:
        raise LookupError(f"enum type {_album_format_pg_name!r} not found; cannot register it")
    register_enum(
        album_format_info,
        conn,
        _db_types.AlbumFormat,
        mapping={member: member.value for member in _db_types.AlbumFormat},
    )
    recording_info_info = CompositeInfo.fetch(conn, _recording_info_pg_name)
    if recording_info_info is None:
        raise LookupError(f"composite type {_recording_info_pg_name!r} not found; cannot register it")
    register_composite(
        recording_info_info,
        conn,
        _db_types.RecordingInfo,
        make_object=_recording_info_make_object,
        make_sequence=_recording_info_make_sequence,
    )
    track_info_info = CompositeInfo.fetch(conn, _track_info_pg_name)
    if track_info_info is None:
        raise LookupError(f"composite type {_track_info_pg_name!r} not found; cannot register it")
    register_composite(
        track_info_info,
        conn,
        _db_types.TrackInfo,
        make_object=_track_info_make_object,
        make_sequence=_track_info_make_sequence,
    )
    disc_info_info = CompositeInfo.fetch(conn, _disc_info_pg_name)
    if disc_info_info is None:
        raise LookupError(f"composite type {_disc_info_pg_name!r} not found; cannot register it")
    register_composite(
        disc_info_info,
        conn,
        _db_types.DiscInfo,
        make_object=_disc_info_make_object,
        make_sequence=_disc_info_make_sequence,
    )
