# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import cast

from psycopg import AsyncConnection

from .._runtime import fetch_many
from ..types.album import Album


@dataclass(frozen=True, slots=True)
class SelectAlbumRowsRow:
    album: Album | None


def decode_select_album_rows(row: Mapping[str, object]) -> SelectAlbumRowsRow:
    return SelectAlbumRowsRow(
        album=None if row["album"] is None else Album.pg_decode(row["album"]),
    )


SQL = """\
select (album.*)::album from album
"""

_SQL = SQL.encode()


async def select_album_rows(
    conn: AsyncConnection[object],
) -> list[SelectAlbumRowsRow]:
    params: dict[str, object] = {}
    return await fetch_many(conn, _SQL, params, decode_select_album_rows)
