# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import cast

from psycopg import AsyncConnection

from .._core import require_array
from .._runtime import fetch_many
from ..types.track_info import TrackInfo
from ..types.disc_info import DiscInfo


@dataclass(frozen=True, slots=True)
class SelectAlbumWithTracksRow:
    id: int
    name: str
    tracks: list[TrackInfo]
    disc: DiscInfo | None


def decode_select_album_with_tracks(row: Mapping[str, object]) -> SelectAlbumWithTracksRow:
    return SelectAlbumWithTracksRow(
        id=cast(int, row["id"]),
        name=cast(str, row["name"]),
        tracks=[TrackInfo.pg_decode(v) for v in cast(list[str], require_array(row["tracks"]))],
        disc=None if row["disc"] is None else DiscInfo.pg_decode(row["disc"]),
    )


SQL = """\
select id, name, tracks, disc
from album
where id = %(id)s
"""

_SQL = SQL.encode()


async def select_album_with_tracks(
    conn: AsyncConnection[object],
    *,
    id: int,
) -> list[SelectAlbumWithTracksRow]:
    params: dict[str, object] = {
        "id": id,
    }
    return await fetch_many(conn, _SQL, params, decode_select_album_with_tracks)
