# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from datetime import date
from typing import cast

from psycopg import AsyncConnection

from .._core import require_array
from .._runtime import fetch_many
from ..types.recording_info import RecordingInfo
from ..types.album_format import AlbumFormat
from ..types.recording_info import RecordingInfo
from ..types.track_info import TrackInfo
from ..types.disc_info import DiscInfo


@dataclass(frozen=True, slots=True)
class UpdateAlbumRecordingReturningRow:
    id: int
    name: str
    released: date | None
    format: AlbumFormat | None
    recording: RecordingInfo | None
    tracks: list[TrackInfo] | None
    disc: DiscInfo | None


def decode_update_album_recording_returning(row: Mapping[str, object]) -> UpdateAlbumRecordingReturningRow:
    return UpdateAlbumRecordingReturningRow(
        id=cast(int, row["id"]),
        name=cast(str, row["name"]),
        released=cast(date | None, row["released"]),
        format=None if row["format"] is None else AlbumFormat.pg_decode(row["format"]),
        recording=None if row["recording"] is None else RecordingInfo.pg_decode(row["recording"]),
        tracks=None if row["tracks"] is None else [TrackInfo.pg_decode(v) for v in cast(list[str], require_array(row["tracks"]))],
        disc=None if row["disc"] is None else DiscInfo.pg_decode(row["disc"]),
    )


SQL = """\
-- Update album recording information
update album
set recording = %(recording)s
where id = %(id)s
returning *
"""

_SQL = SQL.encode()


async def update_album_recording_returning(
    conn: AsyncConnection[object],
    *,
    recording: RecordingInfo | None,
    id: int,
) -> list[UpdateAlbumRecordingReturningRow]:
    params: dict[str, object] = {
        "recording": None if recording is None else recording.pg_encode(),
        "id": id,
    }
    return await fetch_many(conn, _SQL, params, decode_update_album_recording_returning)
