# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from dataclasses import dataclass
from datetime import date

from psycopg import AsyncConnection, Connection
from psycopg.rows import args_row as _args_row

from .. import types as _db_types
from .._runtime import fetch_many as _fetch_many
from ..sync._runtime import fetch_many as _fetch_many_sync

SQL = """\
-- This is an example of a bulk-insert (batch-insert) technique.
-- We pass in all fields as arrays of the same size, and we unnest it to insert multiple rows at once.
insert into album (name, released, format)
select *
from unnest(
  %(name)s::text[],
  %(released)s::date[],
  %(format)s::album_format[]
)
returning id
"""


@dataclass(frozen=True, slots=True)
class InsertMultipleAlbumsRow:
    id: int


async def insert_multiple_albums(
    conn: AsyncConnection[object],
    *,
    name: list[str],
    released: list[date],
    format: list[_db_types.AlbumFormat],
) -> list[InsertMultipleAlbumsRow]:
    params: dict[str, object] = {
        "name": name,
        "released": released,
        "format": format,
    }
    return await _fetch_many(conn, SQL, params, _args_row(InsertMultipleAlbumsRow))


def insert_multiple_albums_sync(
    conn: Connection[object],
    *,
    name: list[str],
    released: list[date],
    format: list[_db_types.AlbumFormat],
) -> list[InsertMultipleAlbumsRow]:
    params: dict[str, object] = {
        "name": name,
        "released": released,
        "format": format,
    }
    return _fetch_many_sync(conn, SQL, params, _args_row(InsertMultipleAlbumsRow))
