# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from dataclasses import dataclass
from datetime import date

from psycopg import AsyncConnection, Connection
from psycopg.rows import args_row as _args_row

from .. import types as _db_types
from .._runtime import fetch_many as _fetch_many
from ..sync._runtime import fetch_many as _fetch_many_sync

SQL = """\
select 
  id,
  name,
  released,
  format,
  recording
from album
where format = %(format)s
"""


@dataclass(frozen=True, slots=True)
class SelectAlbumByFormatRow:
    id: int
    name: str
    released: date | None
    format: _db_types.AlbumFormat | None
    recording: _db_types.RecordingInfo | None


async def select_album_by_format(
    conn: AsyncConnection[object],
    *,
    format: _db_types.AlbumFormat,
) -> list[SelectAlbumByFormatRow]:
    params: dict[str, object] = {
        "format": format,
    }
    return await _fetch_many(conn, SQL, params, _args_row(SelectAlbumByFormatRow))


def select_album_by_format_sync(
    conn: Connection[object],
    *,
    format: _db_types.AlbumFormat,
) -> list[SelectAlbumByFormatRow]:
    params: dict[str, object] = {
        "format": format,
    }
    return _fetch_many_sync(conn, SQL, params, _args_row(SelectAlbumByFormatRow))
