# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime

from psycopg import AsyncConnection, Connection
from psycopg.rows import args_row as _args_row

from .. import types as _db_types
from .._runtime import fetch_many as _fetch_many
from ..sync._runtime import fetch_many as _fetch_many_sync

SQL = """\
-- Demonstrates static query equivalent of dynamic field selection.
-- Boolean flags control which fields are included in the result,
-- returning NULL for fields the caller opts out of.
-- Also demonstrates optional filters and ordering criteria.
SELECT
  album.id,
  CASE WHEN %(include_name)s THEN album.name END AS name,
  CASE WHEN %(include_released)s THEN album.released END AS released,
  CASE WHEN %(include_format)s THEN album.format END AS format,
  CASE WHEN %(include_recording)s THEN album.recording END AS recording,
  CASE WHEN %(include_tracks)s THEN album.tracks END AS tracks,
  CASE WHEN %(include_disc)s THEN album.disc END AS disc
FROM album
LEFT JOIN album_artist ON album_artist.album = album.id
LEFT JOIN artist ON artist.id = album_artist.artist
LEFT JOIN album_genre ON album_genre.album = album.id
LEFT JOIN genre ON genre.id = album_genre.genre
WHERE
  (%(artist_name)s::text IS NULL OR artist.name = %(artist_name)s)
  AND (%(genre_name)s::text IS NULL OR genre.name = %(genre_name)s)
  AND (%(format)s::album_format IS NULL OR album.format = %(format)s)
  AND (%(released_after)s::timestamp IS NULL OR album.released >= %(released_after)s)
  AND (%(name_like)s::text IS NULL OR album.name LIKE %(name_like)s)
ORDER BY
  CASE WHEN %(order_by_name)s THEN album.name END ASC,
  CASE WHEN %(order_by_released)s THEN album.released END DESC
"""


@dataclass(frozen=True, slots=True)
class SelectAlbumWithFiltersRow:
    id: int
    name: str | None
    released: date | None
    format: _db_types.AlbumFormat | None
    recording: _db_types.RecordingInfo | None
    tracks: list[_db_types.TrackInfo] | None
    disc: _db_types.DiscInfo | None


async def select_album_with_filters(
    conn: AsyncConnection[object],
    *,
    include_name: bool,
    include_released: bool,
    include_format: bool,
    include_recording: bool,
    include_tracks: bool,
    include_disc: bool,
    artist_name: str | None,
    genre_name: str | None,
    format: _db_types.AlbumFormat | None,
    released_after: datetime | None,
    name_like: str | None,
    order_by_name: bool,
    order_by_released: bool,
) -> list[SelectAlbumWithFiltersRow]:
    params: dict[str, object] = {
        "include_name": include_name,
        "include_released": include_released,
        "include_format": include_format,
        "include_recording": include_recording,
        "include_tracks": include_tracks,
        "include_disc": include_disc,
        "artist_name": artist_name,
        "genre_name": genre_name,
        "format": format,
        "released_after": released_after,
        "name_like": name_like,
        "order_by_name": order_by_name,
        "order_by_released": order_by_released,
    }
    return await _fetch_many(conn, SQL, params, _args_row(SelectAlbumWithFiltersRow))


def select_album_with_filters_sync(
    conn: Connection[object],
    *,
    include_name: bool,
    include_released: bool,
    include_format: bool,
    include_recording: bool,
    include_tracks: bool,
    include_disc: bool,
    artist_name: str | None,
    genre_name: str | None,
    format: _db_types.AlbumFormat | None,
    released_after: datetime | None,
    name_like: str | None,
    order_by_name: bool,
    order_by_released: bool,
) -> list[SelectAlbumWithFiltersRow]:
    params: dict[str, object] = {
        "include_name": include_name,
        "include_released": include_released,
        "include_format": include_format,
        "include_recording": include_recording,
        "include_tracks": include_tracks,
        "include_disc": include_disc,
        "artist_name": artist_name,
        "genre_name": genre_name,
        "format": format,
        "released_after": released_after,
        "name_like": name_like,
        "order_by_name": order_by_name,
        "order_by_released": order_by_released,
    }
    return _fetch_many_sync(conn, SQL, params, _args_row(SelectAlbumWithFiltersRow))
