# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from dataclasses import dataclass
from datetime import date

from psycopg import AsyncConnection, Connection
from psycopg.rows import args_row as _args_row

from .. import types as _db_types
from .._runtime import fetch_many as _fetch_many
from ..sync._runtime import fetch_many as _fetch_many_sync

SQL = """\
-- Update album recording information
update album
set recording = %(recording)s
where id = %(id)s
returning *
"""


@dataclass(frozen=True, slots=True)
class UpdateAlbumRecordingReturningRow:
    id: int
    name: str
    released: date | None
    format: _db_types.AlbumFormat | None
    recording: _db_types.RecordingInfo | None
    tracks: list[_db_types.TrackInfo] | None
    disc: _db_types.DiscInfo | None


async def update_album_recording_returning(
    conn: AsyncConnection[object],
    *,
    recording: _db_types.RecordingInfo | None,
    id: int,
) -> list[UpdateAlbumRecordingReturningRow]:
    params: dict[str, object] = {
        "recording": recording,
        "id": id,
    }
    return await _fetch_many(conn, SQL, params, _args_row(UpdateAlbumRecordingReturningRow))


def update_album_recording_returning_sync(
    conn: Connection[object],
    *,
    recording: _db_types.RecordingInfo | None,
    id: int,
) -> list[UpdateAlbumRecordingReturningRow]:
    params: dict[str, object] = {
        "recording": recording,
        "id": id,
    }
    return _fetch_many_sync(conn, SQL, params, _args_row(UpdateAlbumRecordingReturningRow))
