# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from datetime import date

from psycopg import AsyncConnection, Connection

from .._runtime import execute_rows_affected as _execute_rows_affected
from ..sync._runtime import execute_rows_affected as _execute_rows_affected_sync

SQL = """\
update album
set released = %(released)s
where id = %(id)s
"""


async def update_album_released(
    conn: AsyncConnection[object],
    *,
    released: date | None,
    id: int,
) -> int:
    params: dict[str, object] = {
        "released": released,
        "id": id,
    }
    return await _execute_rows_affected(conn, SQL, params)


def update_album_released_sync(
    conn: Connection[object],
    *,
    released: date | None,
    id: int,
) -> int:
    params: dict[str, object] = {
        "released": released,
        "id": id,
    }
    return _execute_rows_affected_sync(conn, SQL, params)
