# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from ._generated._core import JsonValue as JsonValue, NoRowError as NoRowError

from ._generated.types.album import Album as Album
from ._generated.types.album_format import AlbumFormat as AlbumFormat
from ._generated.types.disc_info import DiscInfo as DiscInfo
from ._generated.types.recording_info import RecordingInfo as RecordingInfo
from ._generated.types.track_info import TrackInfo as TrackInfo

from ._generated.statements.insert_album import insert_album as insert_album, InsertAlbumRow as InsertAlbumRow
from ._generated.statements.insert_multiple_albums import insert_multiple_albums as insert_multiple_albums, InsertMultipleAlbumsRow as InsertMultipleAlbumsRow
from ._generated.statements.select_album_by_format import select_album_by_format as select_album_by_format, SelectAlbumByFormatRow as SelectAlbumByFormatRow
from ._generated.statements.select_album_by_id import select_album_by_id as select_album_by_id, SelectAlbumByIdRow as SelectAlbumByIdRow
from ._generated.statements.select_album_by_name import select_album_by_name as select_album_by_name, SelectAlbumByNameRow as SelectAlbumByNameRow
from ._generated.statements.select_album_rows import select_album_rows as select_album_rows, SelectAlbumRowsRow as SelectAlbumRowsRow
from ._generated.statements.select_album_with_filters import select_album_with_filters as select_album_with_filters, SelectAlbumWithFiltersRow as SelectAlbumWithFiltersRow
from ._generated.statements.select_album_with_tracks import select_album_with_tracks as select_album_with_tracks, SelectAlbumWithTracksRow as SelectAlbumWithTracksRow
from ._generated.statements.select_genre_by_artist import select_genre_by_artist as select_genre_by_artist, SelectGenreByArtistRow as SelectGenreByArtistRow
from ._generated.statements.update_album_recording_returning import update_album_recording_returning as update_album_recording_returning, UpdateAlbumRecordingReturningRow as UpdateAlbumRecordingReturningRow
from ._generated.statements.update_album_released import update_album_released as update_album_released

__all__ = [
    "JsonValue",
    "NoRowError",
    "Album",
    "AlbumFormat",
    "DiscInfo",
    "RecordingInfo",
    "TrackInfo",
    "InsertAlbumRow",
    "InsertMultipleAlbumsRow",
    "SelectAlbumByFormatRow",
    "SelectAlbumByIdRow",
    "SelectAlbumByNameRow",
    "SelectAlbumRowsRow",
    "SelectAlbumWithFiltersRow",
    "SelectAlbumWithTracksRow",
    "SelectGenreByArtistRow",
    "UpdateAlbumRecordingReturningRow",
    "insert_album",
    "insert_multiple_albums",
    "select_album_by_format",
    "select_album_by_id",
    "select_album_by_name",
    "select_album_rows",
    "select_album_with_filters",
    "select_album_with_tracks",
    "select_genre_by_artist",
    "update_album_recording_returning",
    "update_album_released",
]
