name: Build and deploy artifacts

on:
  push:
    branches:
      - master
      - dev

jobs:

  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the source code
        uses: actions/checkout@v3.0.2




      - name: Init
        run: sudo apt-get update && sudo apt-get install -y wget xz-utils

      - name: Install pGenie
        run: |
          VERSION=1.0.0
          FILE=pgenie-cli-v$VERSION-linux-x64.tar.xz
          wget -q https://github.com/pgenie-io/cli/releases/download/v$VERSION/$FILE
          tar -xf $FILE
          rm $FILE
          mv pgn /usr/local/bin

      # - name: Debug
      #   run: |
      #     curl -v --http1.1 -X POST https://api.pgenie.io/v1 || :
      #     ping -c1 api.pgenie.io || :

      # - run: sudo ethtool -K eth0 tx off rx off

      # - run: pgn --service-url https://bbakoqousu6g9qnpkhh1.containers.yandexcloud.net/
      - run: pgn --service-url https://d5dse1mp8tvk14hqu5cl.apigw.yandexcloud.net
      



      # - name: Build
      #   uses: pgenie-io/cli.github-action@master






      # - name: Deploy
      #   uses: leigholiver/commit-with-deploy-key@v1.0.3
      #   with:
      #     source: artifacts
      #     destination_repo: pgenie-io/demo-artifacts
      #     git_username: github-actions
      #     git_email: github-actions@pgenie.io
      #     deploy_key: ${{ secrets.DEPLOY_KEY }}
